"""added clinic_phone

Revision ID: 3bb046fdcbd1
Revises: 9cd500aaafc9
Create Date: 2025-09-27 18:44:48.728726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb046fdcbd1'
down_revision = '9cd500aaafc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('clinic_phone')

    with op.batch_alter_table('agenda_events', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
