"""Allow NULL doctor_id in consults

Revision ID: 9cd500aaafc9
Revises: dfe0d9822d62
Create Date: 2025-09-24 20:21:44.062074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd500aaafc9'
down_revision = 'dfe0d9822d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda_events', schema=None) as batch_op:
        batch_op.create_index('ix_agenda_events_type', ['type'], unique=False)

    with op.batch_alter_table('consults', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('scheduled_emails', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_emails_send_at', ['send_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_emails_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_emails_user_id'))
        batch_op.drop_index('ix_scheduled_emails_send_at')

    with op.batch_alter_table('consults', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('agenda_events', schema=None) as batch_op:
        batch_op.drop_index('ix_agenda_events_type')

    # ### end Alembic commands ###
